"""criação do banco de dados

Revision ID: 164404424c93
Revises: 
Create Date: 2025-05-24 15:28:54.939530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '164404424c93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_de_envio', sa.DateTime(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    # ### end Alembic commands ###
