"""Criação da tabela atendimento

Revision ID: 4e08501a0d02
Revises: 8cbb2f0a9e24
Create Date: 2025-05-31 17:59:10.985437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e08501a0d02'
down_revision = '8cbb2f0a9e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atendimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('situacao', sa.String(), nullable=True),
    sa.Column('piscina', sa.String(), nullable=True),
    sa.Column('vendedor', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atendimento')
    # ### end Alembic commands ###
