""".

Revision ID: 8cbb2f0a9e24
Revises: d2b8c437a6c8
Create Date: 2025-05-24 17:37:38.398992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cbb2f0a9e24'
down_revision = 'd2b8c437a6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(), nullable=True))
        batch_op.drop_column('numero')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
