"""adicao de secao para falar sobre o cliente(comentario) na tabela clientes

Revision ID: ba570c0675f4
Revises: 164404424c93
Create Date: 2025-05-24 15:36:47.867021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba570c0675f4'
down_revision = '164404424c93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentario', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('comentario')

    # ### end Alembic commands ###
